name: btop
adopt-info: btop
summary: Resource monitor that shows usage and stats
description: |
  Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  C++ version and continuation of bashtop and bpytop.
license: Apache-2.0

base: core24
grade: stable
confinement: strict
compression: lzo

contact: https://github.com/kz6fittycent/btop/issues
issues: https://github.com/kz6fittycent/btop/issues
source-code: https://github.com/aristocratos/btop

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  btop:
    command: usr/local/bin/btop
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - mount-observe
      - process-control
      - system-observe
      - hardware-observe
      - network
      - network-observe
      - home
      - removable-media
      - opengl

parts:
  btop:
    source: https://github.com/aristocratos/btop
    source-type: git
    after:
      - gcc-15
    plugin: make
    build-environment:
      - PATH: $PATH:$CRAFT_STAGE/usr/local/bin    
    make-parameters:
      - CC=gcc-15
      - CXX=g++-15
      - PREFIX=/usr/local
      - STATIC=true #required
      - ADDFLAGS="-D SNAPPED" #required
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

  gcc-15:
    plugin: nil
    override-pull: |
      craftctl default
      wget https://gcc.gnu.org/pub/gcc/infrastructure/gmp-6.2.1.tar.bz2
      wget https://gcc.gnu.org/pub/gcc/infrastructure/mpfr-4.1.0.tar.bz2
      wget https://gcc.gnu.org/pub/gcc/infrastructure/mpc-1.2.1.tar.gz
      git clone --branch releases/gcc-15.1.0 --depth 1 --single-branch https://gcc.gnu.org/git/gcc.git gcc_src
      tar xvf gmp-6.2.1.tar.bz2
      tar xvf mpfr-4.1.0.tar.bz2
      tar xvf mpc-1.2.1.tar.gz
      rm gmp-6.2.1.tar.bz2
      rm mpfr-4.1.0.tar.bz2
      rm mpc-1.2.1.tar.gz
    build-packages:
      - wget
      - git
      - tar
      - build-essential
      - flex
      - bison
    override-build: |
      craftctl default
      export GCC_PREFIX=/snap/gcc/current/usr
      mkdir -p $GCC_PREFIX
      mkdir -p /root/prime/usr
      cd gmp-6.2.1
      ./configure --prefix=$GCC_PREFIX
      make
      make install
      cd ..
      cd mpfr-4.1.0
      ./configure --prefix=$GCC_PREFIX  --with-gmp=$GCC_PREFIX 
      make
      make install
      cd ..
      cd mpc-1.2.1
      ./configure --prefix=$GCC_PREFIX --with-gmp=$GCC_PREFIX --with-mpfr=$GCC_PREFIX
      make
      make install
      cd ..
      mkdir gcc_obj
      cd gcc_obj
      ../gcc_src/configure --prefix=$GCC_PREFIX --with-local-prefix=$GCC_PREFIX --with-gmp=$GCC_PREFIX --with-mpfr=$GCC_PREFIX --with-mpc=$GCC_PREFIX --disable-multilib --host=x86_64-pc-linux-gnu --enable-languages=c,c++,lto
      make -j 4
      make install

    override-stage: |
      craftctl default
      export GCC_PREFIX=/snap/gcc/current/usr
      mv $GCC_PREFIX/* /root/prime/usr/
      env >  /root/prime/artifact_generated_at_stage.sh
      
    override-prime: |
      craftctl default
      env >  /root/prime/artifact_generated_at_prime.sh
 
